version: "3"

services:
  ubuntu_20.04:
    image: lightcxx/ubuntu_20.04
    build:
      context: .
      dockerfile: ubuntu_20.04.Dockerfile

  test-clang_10-ubuntu_20.04:
    depends_on: [ubuntu_20.04]
    image: lightcxx/ubuntu_20.04
    volumes: [../..:/code]
    environment: [CC=clang,CXX=clang++]
    command: /code/tools/docker/check.sh clang_10-ubuntu_20.04

# TODO: This doesn't work yet, first error is that we're using <stdatomic.h> in C++ code.
#  test-gcc_9-ubuntu_20.04:
#    depends_on: [ubuntu_20.04]
#    image: lightcxx/ubuntu_20.04
#    volumes: [../..:/code]
#    environment: [CC=gcc,CXX=g++]
#    command: /code/tools/docker/check.sh gcc_9-ubuntu_20.04
